### ISSUE TITLE
Adjust for displaced or absent regions

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/VisuAlign#10]
The ability to remove/adjust parts of template showing areas not visible or displaced in the section image.

**Comment by Tevemadar** [comment]
Is this about manually toggling areas on/off in a list, like in ITK Snap, or MeshView?

**Comment by Tevemadar** [comment]
Is this about manually toggling areas on/off in a list, like in ITK Snap, or MeshView?

**Comment by Majpuc** [comment]
Not exactly. This was described for QNII in the former plan. It is about cutting out parts of the atlas...which don't seem realistic.
Hiding some missing regions could be implemented but not a priority.

**Comment by Majpuc** [comment]
Not exactly. This was described for QNII in the former plan. It is about cutting out parts of the atlas...which don't seem realistic.
Hiding some missing regions could be implemented but not a priority.
