### ISSUE TITLE
QuickNII with developmental atlases

### ISSUE THREAD

**Issue by ingvildeb** [Neural-Systems-at-UIO/VisuAlign#100]
I came across some developmental brain atlases where the segmentations more closely resemble what we have in the adult CCF and was wondering if we could implement these in QuickNII. Volumes and two label files are found at the neuroinf server: Y:\Dopamine_receptors\devbrains_newmaster_nifti\For_QuickNII

Would be great to have the both label files implemented, as alternative color schemes.

Thanks in advance!

Ingvild

**Comment by Tevemadar** [comment]
The segmentation volumes, like P28_label_rev.nii.gz contain at least one unknown label, it's value is 2656, and it can be viewed at 222,262,228 in ITK Snap (1-based coordinates. For old versions of ITK Snap, the coordinates are less by 1). I tried to be creative, but besides that the available label files do not contain such value, the full Allen ontologies (http://api.brain-map.org/api/v2/structure_graph_download/17.json for developing mouse or http://api.brain-map.org/api/v2/structure_graph_download/1.json for the adult) do not use such label value for any purpose either. (Haven't tried all of them, but Adult_label_rev.nii.gz uses this label value too)

**Comment by ingvildeb** [comment]
Hi Gergely,

thanks for letting me know, I will check this out and either name the label or reassign its voxels to another one in the segmentation file (depends on what this is). Is there a way I can systematically check whether there are other such instances? Will it be sufficient to open the segmentation and label file in ITK-snap and see if there are any unnamed labels showing up in the label editor?

**Comment by Tevemadar** [comment]
Hi, yes, ITK Snap can tell. The Label Editor does not show unnamed lables, but the Volumes and Statistics (also in the Segmentation menu) does. By glancing at it, this is the only rogue label in P28. And used by 52 voxels.

**Comment by ingvildeb** [comment]
Thanks and no problem, I think I managed to find them all (at least there is no Label 2656 showing up in volumes and statistics now), and it was present in all the volumes. I've re-labelled the voxels with existing IDs in all the volumes. Fingers crossed there are no more errors.

**Comment by Tevemadar** [comment]
```NESYS_Tools\QuickNII\DevMouse\QuickNII-DevMouse-2021-01.zip``` is the package containing them. Batch files (```Adult.bat```, ```P7.bat``` ... ```P28.bat```) can be used to start one.

**Comment by ingvildeb** [comment]
Thanks for this. I had a look and it seems like all the labels are in the wrong place (this is true for all of them). Is there a problem with the label file or just something that has gone wrong in the process?

**Comment by Tevemadar** [comment]
No, it's just the same bug I ran into last time, then forgot it. The package is fixed now.

**Comment by ingvildeb** [comment]
Wonderful, these look as they should. I will test them more thoroughly in the weeks to come!
