### ISSUE TITLE
Error in Meshview WHS naming

### ISSUE THREAD

**Issue by ingrre** [Neural-Systems-at-UIO/VisuAlign#106]
There is an error in the atlas naming in the following version: 
https://www.nesys.uio.no/MeshView/meshview.html?atlas=WHS_SD_rat_atlas_v2

It seems the name labels of CA1 and CA3 are swapped (so CA1 should be CA3 and vice-versa). 
Labelling is correct in atlas v3 version.

**Comment by Tevemadar** [comment]
Fixed on [NeSys](https://www.nesys.uio.no/MeshView/meshview.html?atlas=WHS_SD_rat_atlas_v2), [GitHub](https://github.com/Tevemadar/meshview-demo/blob/master/WHS_SD_rat_atlas_v2.json) and [apps](http://meshview-meshview.apps.hbp.eu/)
