### ISSUE TITLE
Check buttons

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/VisuAlign#11]
Exit button is not closing the sw
Remove save button if not in use

**Comment by Tevemadar** [comment]
Exit button exits application
Save button is removed
Close button closes series after confirmation
About button displays popup with version and dev/funding info.

**Comment by sharoncy** [comment]
The current solution to this problem is hemisphere masks generated with QMask. We can close this for now. 04.05.21.
