### ISSUE TITLE
Localizoom links (nonlinear)

### ISSUE THREAD

**Issue by ingvildeb** [Neural-Systems-at-UIO/VisuAlign#110]
One more dataset with nonlinear anchorings available. JSON files are here: Z:\HBP_Curation\QuickNII_projects\Projects\Incomplete_projects\2019_Dopamine_receptors_developing_mice\D2R\P70\Nonlinear_JSONS

Navigator blocks:
1362_5286_7528 (subject D123)
1362_5287_7529 (subject D125)
1362_5290_7536 (subject D130)
1362_5292_7538 (subject D146)
1362_5306_7554 (subject D147)

Thanks!

**Comment by Tevemadar** [comment]
https://www.nesys.uio.no/NonLinTest/filmstripzoom.html?atlas=300100&series=7528
https://www.nesys.uio.no/NonLinTest/filmstripzoom.html?atlas=300100&series=7529
https://www.nesys.uio.no/NonLinTest/filmstripzoom.html?atlas=300100&series=7536
https://www.nesys.uio.no/NonLinTest/filmstripzoom.html?atlas=300100&series=7538
https://www.nesys.uio.no/NonLinTest/filmstripzoom.html?atlas=300100&series=7554
