### ISSUE TITLE
MeshView v0.8 - user defined sections and hidden outline

### ISSUE THREAD

**Issue by marovst** [Neural-Systems-at-UIO/VisuAlign#114]
We like to request the following changes to MeshView v0.8 (https://www.nesys.uio.no/MeshView/meshview.html?atlas=ABA_mouse_v3_2017_full ):

1. An option to cut imported point clouds in user-defined sections with a user-defined thickness (in the newest version of MeshView). This option is available in a previous version of MeshView (https://www.nesys.uio.no/MeshView/meshviewx.html?atlas=ABA_mouse_v3_2017_full ). Here it is done by cutting in "Cloud only" and adjusting the thickness of the slice by a slider. See attached image for explanation of what function we want to implement from previous version of MeshView.
![OldVersion_MeshView](https://user-images.githubusercontent.com/34418916/107115101-8741f180-686a-11eb-8aa5-9f81629748b5.PNG)
2. View imported point clouds without structural outlines, or the option to make it "invisible" for the eye (turn off structural outline) while still keeping the bounding box.

**Comment by Tevemadar** [comment]
A version with creative name "meshviewy" is available at the same location now, so https://www.nesys.uio.no/MeshView/meshviewy.html?atlas=ABA_mouse_v3_2017_full

**Comment by Majpuc** [comment]
@marovst can you validate?

**Comment by marovst** [comment]
@Majpuc This works as intended. Thank you for the help.
