### ISSUE TITLE
Transfer of hierarchy info between QControl and Nutil

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#115]
Option to export a file containing the list of regions at the hierarchy level that is selected in QControl, with a list of IDs belonging to each of these regions. I have described this in more detail in an email sent 10.02.21.

**Comment by Tevemadar** [comment]
```NESYS_Tools\QControl-v0.5``` has an **Export hierarchy sheet** function (part of File menu). It creates a tabulator-separated text file (```_regions.txt``` ending) with names, RGB colors and atlas ids. Color names are not generated, insert a line if necessary.

**Comment by sharoncy** [comment]
This is great, thanks. Validated 10.03.21.
