### ISSUE TITLE
Missing chunks or images

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/VisuAlign#116]
In this example, there are missing images or chunks
http://localizoom-localizoom.apps-dev.hbp.eu/filmstripzoom.html?atlas=ABA_Mouse_CCFv3_2017_25um&series=Test/C19_anchoring_nonlinear.json&pyramids=imgsvc-7274cfc1-e882-1b35-e4a7-6514d47d8216

**Comment by Tevemadar** [comment]
Sheet updated, some uploads are missing files, some early uploads are missing a lot of files.

**Comment by Majpuc** [comment]
Could you flag the faulty containers in the sheet and I will re-ingest them.

**Comment by Majpuc** [comment]
Issue is followed up by Maja Puchades. In contact with Marc Morgan's team
