### ISSUE TITLE
Version information

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/VisuAlign#12]
Add information about sw version in Help

**Comment by Tevemadar** [comment]
Popup displayed by About button contains version information.

**Comment by Tevemadar** [comment]
Fixed on Nov 12 already, in ```VisuAlign-v0_8-WHS_Rat_v3_fix.zip``` (and ```VisuAlign-v0_8-WHS_Rat_v3_fix.dmg``` for Mac).
