### ISSUE TITLE
MeshView v0.8 - new enhancements

### ISSUE THREAD

**Issue by marovst** [Neural-Systems-at-UIO/VisuAlign#123]
I would like to request two new enhancements:
1. The option to view point clouds (with activated slice function) without meshes.
2. The option to view one side of the brain and hide the other side of the brain (see attached image). 

![image](https://user-images.githubusercontent.com/34418916/110123227-eab73480-7dc0-11eb-8890-89cd52c1d8dd.png)

**Comment by Tevemadar** [comment]
Just a recap of candidates
https://www.nesys.uio.no/MeshView/meshviewy.html?atlas=ABA_mouse_v3_2017_hindbrain
https://www.nesys.uio.no/MeshView/meshviewy.html?atlas=ABA_mouse_v3_2017_L
https://www.nesys.uio.no/MeshView/meshviewy.html?atlas=ABA_mouse_v3_2017_Lh
https://www.nesys.uio.no/MeshView/meshviewy.html?atlas=ABA_mouse_v3_2017_R
https://www.nesys.uio.no/MeshView/meshviewy.html?atlas=ABA_mouse_v3_2017_Rh

**Comment by Majpuc** [comment]
@marovst can you validate?

**Comment by marovst** [comment]
@Majpuc These versions have been validated and work great. Thank you for the help.
