### ISSUE TITLE
_stats.txt: save request. File name is not updated to reflect new series descriptor

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#124]
In QControl v6, the export statistics button automatically saves the stats.txt file in the same folder as the JSON file. It would be better if users could specify the save location and file name , otherwise the files are overwritten if changes are made and the export statistics button is pressed again. I sometimes want to compare old and new files. I tried to get round this by changing the name of the QControl.JSON file and exporting the stats again. However, the stat.txt file name does not update in line with the JSON file name, but still overwrites the old files.

**Comment by Tevemadar** [comment]
Fixed in the updated release of V0.6.
