### ISSUE TITLE
_regions.txt: save request. File name is not updated to reflect new series descriptor

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#126]
Currently the file automatically saves to the same location as the JSON with the file name: series_description_regions.txt. However, if i update the series_descriptor, the name of the _regions.txt is not updated in line with the new name. Ideally, I would like to be able to specify the save name and location.

**Comment by Tevemadar** [comment]
Fixed in the updated release of V0.6.
