### ISSUE TITLE
QControl: request for progress tracker.

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#127]
It is hard to keep track of which sections have been updated in QControl (for example, partially filled in) and those that have been pre-filled only. It would be useful if QControl could track this in a similar way to QuickNII, for example: display a red question mark when no changes have been made, display an orange symbol when it has been partially filled in, display green tick when mark up is complete. I'm sure there are other ways to track progress, if you have other ideas we can discuss this at the friday meeting.

**Comment by Tevemadar** [comment]
v0.7: progress tracking, simple text showing current section as "Clear" or "Changed" and showing the total number of changed sections.
