### ISSUE TITLE
QControl: hierarchy lock. 

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#128]
As changes to the hierarchy structure may invalidate markers that have been placed on the sections, it would be great if the hierarchy would lock automatically as soon as markers have been applied. This would force users to select the hierarchy level as the first step before entering markers, and would ensure markers are not invalidated inadvertantly by changes to the hierarchy.  

The "reset" button could be used to unlock the hierarchy.

**Comment by sharoncy** [comment]
It would also be useful to have a button to override the lock system without markers being deleted. For example, if I want to adjust the hierarchy for regions that have not been considered yet (for example, the cerebellum, when I have only placed markers in the most anterior regions). I'm not sure how to best implement all this in practise. The request for a lock is more important than an override button, just thought I'd mention it in case you have ideas for implementation.

**Comment by Tevemadar** [comment]
v0.7: hierarchy locks when markers are placed, also applies to loading series with user-placed markers, related to #127
Lock can be manually set/clear via a separete menu, "Lock"
Adjusting hierarchy won't affect markers, users can manually reset the entire series with the existing menu commands.
