### ISSUE TITLE
Region level editing

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/VisuAlign#13]
As in the flash version, we should be able to edit region color and it's transparency at the region level.

**Comment by Tevemadar** [comment]
Done in v0.7

**Comment by Majpuc** [comment]
Ok. 20.10.2020

**Comment by Majpuc** [comment]
In addition, I have the same issue on another series, running all locally. It seems to be an "Exception in thread "JavaFX Application Thread" java.lang.NullPointerException"
![image](https://user-images.githubusercontent.com/46992863/98811936-eafe7f00-2421-11eb-8ced-e717de02868c.png)

**Comment by Tevemadar** [comment]
NESYS_Tools\QNonLin-Standalone does not produce errors with TG5174_final_cur281020.json, I paged through all 78 sections.
A thing which may matter: WHSv3 atlas has been updated on the 23rd of January. Older copies of VisuAlign will die on some of the sections where the ear is visible (around 62-63 perhaps).

**Comment by Majpuc** [comment]
I have downloaded VisuAlign this summer, so it is not an old version. Could it be something else? It behaves differently on my laptop and the lab PC. Maybe I can show you?

**Comment by Tevemadar** [comment]
NITRC versions have been updated. Duplicate of https://github.com/Neural-Systems-at-UIO/VisuAlign/issues/19
