### ISSUE TITLE
QControl: add extra marker for flagging areas with tissue damage

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#132]
Currently there are three markers in QControl: accurate (green tick), inaccurate (red cross) and uncertain (question mark). Would it be possible to add a fourth marker for marking up damaged tissue? Brianna suggested a blue cross. Maybe titled: tissue damage or just damage. It would be useful to be able to flag damaged tissue, and to be able to differentiate that from regions with incorrect anchoring. This obviously has an impact on the output, as an extra column would have to be added for each region, so not sure how much work this is. Let me know if it's a problem.

**Comment by Tevemadar** [comment]
v0.7 has been updated with "Damaged" marker, blue `x`. It also appears in statistics, and for now it's simply blue in the overview mode. Overview mode got its menu item, the `Space` bar still works. (And 'Lock' menu is renamed to 'View').
