### ISSUE TITLE
Enable import of customised hierarchy without deleting the "damage" markers.

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#135]
Enable import of a customised hierarchy without deleting/invalidating the "damage" markers. The "damage" markers will only be used to mark up areas with tissue damage or artifacts such as air bubbles and so are not invalidated by changes to the hierarchy. This feature would be very useful for quality control of the tissue.

**Comment by Tevemadar** [comment]
Importing hierarchy in v0.7 does not modify existing markup from now.
