### ISSUE TITLE
Short keys for each QControl marker for enhanced usability

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#137]
It would be great with short keys for the accurate, inaccurate, uncertain and damage markers.

**Comment by Tevemadar** [comment]
v0.7 has been updated  with hotkeys:

- ```1``` - N/A
- ```2``` - Accurate
- ```3``` - Inaccurate
- ```4``` - Uncertain
- ```5``` - Damaged
