### ISSUE TITLE
Export stats bug

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#139]
I think there are inconsistencies in the stats output, which I'd like to investigate further, but I came across a problem with "export statistics" and so am unable to continue testing. Basically, QControl fails to save a statistics file even though it looks like everything is fine. The"export hierarchy sheet" works fine. The files are here Z:\HBP_Analytics\QControl\QControl_GroundTruthData\H_3sections_customised.json. Would you check if it's a QControl bug or if there is an error in the JSON file? I've tried closing QControl and reopening but it still won't export stats for this file. Everything looks fine otherwise.

**Comment by sharoncy** [comment]
To give you a bit of background the dataset was created as a ground truth dataset. I intend to mark up and manually count the markers for a very coarse level of the hierarchy. I started this process and couldn't get the numbers to match up and so simplified it further to make sure the mismatch wasn't due to a counting error on my part, but now I can't export stats. So not sure what's happening here.

**Comment by Tevemadar** [comment]
Thanks, it was a subtle one: export worked after paging through the sections, but not before. Should be okay now.

**Comment by Majpuc** [comment]
@sharoncy could you validate if this is fixed?

**Comment by sharoncy** [comment]
This is fine. Close 03.09.21
