### ISSUE TITLE
Atlas map version control for QUINT

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#140]
As far as I'm aware there is no way to trace back the atlas version based on the atlas maps generated with VisuAlign or QuickNII. It's a repeating issue that users generate atlas maps and then try to run Nutil Quantifier with the wrong version of the atlas, which gives incorrect results. This is only detected by the user if they are thorough and check through all the output images and reports. It's happened several times that users are certain that they have used a certain atlas version but on closer investigation by us it turns out they've used something else. There is clearly a need for version control here. Something to discuss at the SW meeting @Tevemadar @leuat

**Comment by sharoncy** [comment]
The atlas maps from VisuAlign contain version info, the atlas maps from QuickNII do not and it is not possible to implement this. Both the JSON and XML files contain version info. Ideally we should implement support for automatic version recognition in Nutil Quantifier, either from the JSON/XML file or based on the atlas maps. No conclusion made at this point but this should be taken into account in future developments.

**Comment by Majpuc** [comment]
This issue is closed on 10Nov 2021. open a new issue if needed
