### ISSUE TITLE
QControl: statistics output

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#141]
QControl currently exports counts for all sections, even those that have not been changed. It would be better if Nutil only exports output for sections with changed counts with everything else blank. It is impossible to tell from the statistics file whether the marker numbers are correct or correspond to the autofill only.

**Comment by sharoncy** [comment]
Not a priority. I will close this issue for now. 06.01.22.

**Comment by Tevemadar** [comment]
> It would be better if Nutil only exports

I'm not sure why I was the assignee for a Nutil feature anyway.

**Comment by sharoncy** [comment]
Sorry, that was a typo, it was a QControl request. "it would be better if QControl...". But no worries, not a priority.
