### ISSUE TITLE
Import of coordinate of point clouds in WHSv3 don't work

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/VisuAlign#143]
Z:\HBP_Analytics\Nutil_Quantifier\CrossSeeds\CrossSeeds2_762_3166_4248_r4753_1D1\Plaque_only\output_1D1_coord_only\Coordinates

Could not make it work with https://www.nesys.uio.no/MeshView/meshview.html?atlas=WHS_SD_rat_atlas_v3

**Comment by Tevemadar** [comment]
Works now. Needs clearing browser cache.
Temporarily available as https://www.nesys.uio.no/MeshView/meshview.html?atlas=WHSv3 too, it can be used now if clearing browser cache is problematic, but will be removed in the future.
