### ISSUE TITLE
Add developmental atlases to QControl (+ change the name to QCAlign!)

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#146]
- @ingvildeb has asked if the developmental atlases could be added to QControl?
- I'd also like the name changed to QCAlign. 

Great if you could release a new version @Tevemadar with the name updated (the name is currently QQuality v0.7 inside the tool), with the developmental atlases added if possible. Thanks

**Comment by Tevemadar** [comment]
Looked into this and finally found the necessary utility (haven't used it for 1.5 years or so).
However then I noticed that we only have a regular, flat ITK label file in `Dopamine_receptors\Developmental_atlases\devbrains_newmaster_nifti\Resampled-reoriented-volumes`, while QCAlign needs a hierarchy tree to work with. Do we have such hierarchy?
The only similar thing I'm aware of is Allen's "Developing Mouse Brain Atlas" ontology, but it does not match with the label file.

**Comment by sharoncy** [comment]
Thanks for looking into this. I'll ask Ingvild as she's the one who made the request. If these is no hierarchy tree available is it possible to implement the tool without a hierarchy? She was interested to use the tool for QC of the brain tissue and of the histological slice images. This would work fine with a flat atlas structure as the atlas delineations are switched off for the assessment.

**Comment by sharoncy** [comment]
FYI @Tevemadar : I actually have 2 more requests relating to QCAlign that would be great to have implemented before we publish. I'll post a separate ticket.

**Comment by ingvildeb** [comment]
The structure names in this label files should be similar to those found the Allen CCF ontology, although I think the IDs are different. Would it work to use what is available for the adult?

**Comment by Tevemadar** [comment]
`NESYS_Tools\QControl-v0.7` has developmental atlases now available for testing, AMBA-DEV-P7, P14, P21 and P28, without actual hierarchy. However I'm not sure if this is very useful this way.
> Would it work to use what is available for the adult?

No, those are even more different than the "Developing Mouse Brain Atlas" ontology.

**Comment by sharoncy** [comment]
Thanks Gergely. Would you change the names across the board to QCAlign please? I'll take a look.

**Comment by sharoncy** [comment]
I've been in contact with Ingvild. She's like to create a hierarchy for the dev atlases. What sort of input file do you need to implement this in QCAlign? Format, file structure, etc? I suspect it's the tree.json that is part of QCAlign, but this looks complicated to generate manually. Do you have any advice on how to do this? @ingvildeb @Tevemadar

**Comment by Tevemadar** [comment]
Issues remaining open forever are apparently getting criticism. As developmental atlases have been added, and a very different question arose, "Do we have a user-friendly editor for atlas hierarchies?" (we don't), I close this one now.
