### ISSUE TITLE
QCAlign: request for damage markers.

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#152]
The output of the "damage" assessment currently looks like this:
![image](https://user-images.githubusercontent.com/30626642/167116881-303b3e08-34f7-4217-9805-1b19d286ccca.png)

For each brain region, I calculate % damage as follows: no. of "damage" markers / total no. of markers in the region.
As an example, for isocortex = 590 / (590 +31278) *100 = 1.8% 

I would like to be able to perform this calculation for the whole brain without having to substract the "clear label" counts from the "total" counts. Would it be possible to either change the "total" to represent the marker counts within the atlas maps for the whole series, or to add a new "structure" with marker counts within the atlas maps for the whole series. 

I have done my best to understand the output but please let me know if I've misunderstood something.

**Comment by Tevemadar** [comment]
Please test if the updated NESYS_Tools\QCAlign-v0.8 provides the numbers you have.

**Comment by sharoncy** [comment]
Thanks Gergely, this is great. Numbers are exactly as they should be. 
Would you change the **Total** label to **Total grid**, and change **Total non-clear** to **Total atlas** please? That would make it easier for users to understand.
Thanks.

**Comment by Tevemadar** [comment]
I think it's done. Please have a look just to be sure, but I haven't touched the numbers so they're expected to be fine.

**Comment by sharoncy** [comment]
Thanks! This has been tested, works great. Issue closed on 18.05.22.
