### ISSUE TITLE
Make specific extension for WebAlign to hide ingestion_information.json

### ISSUE THREAD

**Issue by PolarBean** [Neural-Systems-at-UIO/VisuAlign#171]
add text to explain that the file “ingestion_information.json” should NOT be used here (this is the ingestion metadata file)

**Comment by Majpuc** [comment]
If possible make sure only the .waln files show up as possible files to open. By nov 30th, the directories of precomputed files are also actionable and don't lead to anything

**Comment by Tevemadar** [comment]
Done as #174
