### ISSUE TITLE
Problem with the flat file

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#172]
![Image](https://user-images.githubusercontent.com/30626642/193258804-656fd73e-1778-4774-b2a7-9dd22d2337d9.png)

**Comment by Tevemadar** [comment]
Fixed.

**Comment by sharoncy** [comment]
Fab. I'll test.

**Comment by sharoncy** [comment]
I re-exported atlas files from WebAlign and ran through Nutil. The analysis worked as expected. Validated 10.10.22.
