### ISSUE TITLE
Add WHSv4 to target atlas

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#176]

**Comment by Majpuc** [comment]
Flat export is an issue. If Nutil can read the new flat file format, no fix is necessary

**Comment by Tevemadar** [comment]
Is there a need for supporting multiple atlas versions at a time? Or can it be a single WHS Rat atlas, always the newest one? Of course I would still display that it's v4 in particular, so people would know, just when v5 comes out, it would replace the atlas - so the next time someone opens a rat registration, it would load v5.

**Comment by Tevemadar** [comment]
WebAlign and WebWarp supports WHSv4 now.
