### ISSUE TITLE
Jackson Lab_ Brianna_ bug with stripes in Non-lin Visualign

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/VisuAlign#19]
As I have adjusted more brain registrations using the non-linear tool, I have come across a potential glitch several times and I wanted to see whether this is a common occurrence. When this error happens all of the markers disappear from the anchoring and the atlas viewer freezes and borders become fragmented (as seen in the screenshots).
![bilde](https://user-images.githubusercontent.com/46992863/71895710-148bb180-3152-11ea-96d2-a59044c819c9.png)

**Comment by Tevemadar** [comment]
Exit button exits application
Save button is removed
Close button closes series after confirmation
About button displays popup with version and dev/funding info.

**Comment by Majpuc** [comment]
This will be tested by Brianna when she get the new version of VisuAlign next week
