### ISSUE TITLE
Implement a report with calculations befoe and after non-lin adjustment

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/VisuAlign#20]
Request of some quantification report for the registration

**Comment by Majpuc** [comment]
A report file with calculations between the linear registration (QuickNII) and after non-linear registration (VisuAlign). We don't have ground truth registration but we assume that after non-linear registration, you will be pretty close to that. So if we assume that the non-linear registration is 100%, the report will calculate how many pixels have been moved and the "stable %"  number gives you an average  percentage of how the first registration was (QuickNII alone).

**Comment by Tevemadar** [comment]
Popup displayed by About button contains version information.
