### ISSUE TITLE
Enable 2 cuts in MeshView

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/VisuAlign#23]
High priority!!!

Martin needs to be able to load several point clouds and cut the atlas twice in order to see points in this slice only. Martin can give more details on how the output should look like.

**Comment by Majpuc** [comment]
Please give this a high priority.

**Comment by Majpuc** [comment]
http://www.nesys.uio.no/MeshView/meshviewx.html?atlas=ABA_mouse_v3_root

It is working only on Chrome, not Firefox.

**Comment by Majpuc** [comment]
Cannot make this work even in chrome..

**Comment by marovst** [comment]
I'm unable to make it work in chrome, firefox and microsoft edge. Is this function still supported?

**Comment by Majpuc** [comment]
@Tevemadar Could you have a look at this issue again?

**Comment by Majpuc** [comment]
@Tevemadar the two cut function is not present in the versions here:https://www.nesys.uio.no/MeshView/ 
even using Chrome

**Comment by marovst** [comment]
We have several new versions with the name meshview**y**.

Other issues on the matter:
https://github.com/Neural-Systems-at-UIO/VisuAlign/issues/114
https://github.com/Neural-Systems-at-UIO/VisuAlign/issues/123

Link to viewer with updated cutting tool:
https://www.nesys.uio.no/MeshView/meshviewy.html?atlas=ABA_mouse_v3_2017_full
