### ISSUE TITLE
Difference in coordinate positions between old and new MeshView

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/VisuAlign#26]
A user in HBP from Pennartz group working with electrode tract positions noticed that his electrode position was displaced in the new MeshView (see scrennshot)
[PennartzJulien14_updated_Meshview_aligned.txt](https://github.com/Neural-Systems-at-UIO/VisuAlign/files/4071299/PennartzJulien14_updated_Meshview_aligned.txt)
![Pennartz_old MeshView](https://user-images.githubusercontent.com/46992863/72527745-c53c3400-3869-11ea-812f-7260eaead1b4.PNG)
![Pennartz_new MeshView](https://user-images.githubusercontent.com/46992863/72527747-c53c3400-3869-11ea-9a82-2baddae0a565.PNG)

**Comment by Tevemadar** [comment]
Mirroring controls have been hidden behind a "Mirror x-axis" checkbox, so they do not mislead users into being atlas-selection.
