### ISSUE TITLE
Online QuickNII for SGA3

### ISSUE THREAD

**Issue by Tevemadar** [Neural-Systems-at-UIO/VisuAlign#30]

**Comment by Majpuc** [comment]
New online registration tool: proposed name: WebAlign
Features:
- linear and non-linear registration of image series coming from chunk containers
- User interface looking like localizoom with filmstrip and atlas overlay
- possibility to annotate
- coupled to MeshView tool
- saving is coupled to user private space on CSCS

**Comment by Majpuc** [comment]
status 03.09.2021 WebAlign is ongoing

**Comment by Majpuc** [comment]
30.11.2022. WebAlign is now deployed and has its own issue tracking channel
