### ISSUE TITLE
New script for creating customized localizoom links

### ISSUE THREAD

**Issue by ingrre** [Neural-Systems-at-UIO/VisuAlign#32]
We ask for a script that can create one localizoom link (URL) based on a selected number of N3-blocks.

**Comment by Majpuc** [comment]
The use case here is the H201_Sagittal_sections_rat dataset (animal 2786 in N3). Ingrid would like to combine all images in the blocks a, b and c in one Localozoom link without doing it manually (i.e. write all the image numbers in the string)

**Comment by Tevemadar** [comment]
Feature can be tested at http://www.nesys.uio.no/MultiBlock
"series" field in the middle of links support multiple block ID-s, separated by commas, like 425,427 in this example:
http://www.nesys.uio.no/MultiBlock/filmstripzoom.html?atlas=300000&series=425,427&preview=ABAMousev2Preview.png
The ID-s can be added either at the "login" page when copy-pasting the original N3 link, or afterwards when the viewer is open. Example uses public blocks, no login is necessary.

When merging blocks, viewer follows this procedure:

1. If `_s123` numbering is present in a name, that is going to be the sequence number for the image
2. If `_s123` numbering is not present in a name, viewer checks if a sequence number is provided in N3 descriptor
3. When images have no numbering information, they are ordered by name

**Comment by Majpuc** [comment]
Hi Gergely,

Thanks very much. I have asked them to test.

Best, Maja

**Comment by ingrre** [comment]
Thanks, this is great! As localizoom links for H201 is not uploaded yet, I tested with two series belonging to project 1301: Atlas_of_parvalbumin_and_somatostatin, animals: 25203 and 25204, blocks: 6006 and 6066.

How do I adapt the URL to WHS? (in a foolish attempt I tried replacing the "ABAMousev2Preview" with "WHSRatv2Preview", with no result). 

MultiBlock URL: 
http://www.nesys.uio.no/MultiBlock/filmstripzoom.html?atlas=300000&series=6006,6066&preview=WHSRatv2Preview.png

**Comment by Majpuc** [comment]
You forgott to change the number of the atlas. It is 200000 for WHSv2.
http://www.nesys.uio.no/MultiBlock/filmstripzoom.html?atlas=200000&series=6066,6006&preview=WHSRatv2Preview.png

**Comment by Majpuc** [comment]
Remember that the links will only work for public dataset. 
For example:  
 http://www.nesys.uio.no/MultiBlock/filmstripzoom.html?atlas=200000&series=1941,1961&preview=WHSRatv2Preview.png

**Comment by Tevemadar** [comment]
> How do I adapt the URL to WHS? (in a foolish attempt I tried replacing the "ABAMousev2Preview" with "WHSRatv2Preview", with no result).

The best practice is to open one of the blocks in question with LocaliZoom in Navigator, and use that link with the "login" page (for private datasets), or copy its parameters starting with the question mark (for public datasets). I do not remember these parameters from the top of my head either.

**Comment by ingrre** [comment]
This is great. Thank you very much! 

I didn't get how to solve this for private datasets. What do you mean by 'using the link with the "login" page'? Take blocks 6006 and 6066 as an example. This is the localizoom link for 6006: http://cmbn-navigator.uio.no/navigator/filmstripzoom/filmstripzoom.html?atlas=200000&series=6006&preview=WHSRatv2Preview.png 

Is there something in this URL that I should copy-paste into the multiblock URL?

**Comment by ingrre** [comment]
Had a quick talk to Maja about it, which cleared things up. Issue can be closed now. Thank you for providing this solution!
