### ISSUE TITLE
"Hide" button removes both points and Meshes

### ISSUE THREAD

**Issue by marovst** [Neural-Systems-at-UIO/VisuAlign#35]
In the new version of MeshViewx I cannot view points without meshes like in the previous version. 

http://www.nesys.uio.no/MeshView/meshviewx.html?atlas=ABA_mouse_v3_root

**Comment by Tevemadar** [comment]
MeshView and "MeshViewX" has been extended to support displaying of point clouds when all atlas meshes are hidden. When this happens, orbit centre and scale uses dimensions of the entire atlas.
