### ISSUE TITLE
LocaliZoom-link for VisuAlign (non-linear registration) output

### ISSUE THREAD

**Issue by blixilla** [Neural-Systems-at-UIO/VisuAlign#38]
Would it be possible to set up LocaliZoom with atlas maps created with VisuAlign? 

I have 4 series I would like to set this up for. The first one can be found here: Y:\hbp-02421\QuickNII_merged\new_H200_QuickNII_merged
The output from VisuAlign is this file: H200_TimmThionin_horizontal_IR_1_US_VisuAlign_CHB.json

**Comment by Tevemadar** [comment]
LocaliZoom-NonLinear can load VisuAlign JSON data now.

**Comment by Tevemadar** [comment]
@blixilla @Majpuc please provide actual data, N3 block ID + VisuAlign JSON pairs. Preferably public.

**Comment by ingrre** [comment]
Hope the set of files below will work:

File 1: H200_TimmThionin_horizontal_IR_1_US_VisuAlign_CHB.json 
File 2: H441_TimmThionin_horizontal_IR_gjeldende_US_VisuAlign_CHB.json 
Location: lagringshotell - Y:\hbp-02421\QuickNII_merged\  (also provided here [Arkiv.zip](https://github.com/Neural-Systems-at-UIO/VisuAlign/files/4360127/Arkiv.zip))

N3 - blocks for H200: 5946 og 5947 
N3 - blocks for H441: 5255 og 5256 

[Arkiv.zip](https://github.com/Neural-Systems-at-UIO/VisuAlign/files/4360127/Arkiv.zip)

**Comment by Tevemadar** [comment]
@ingrre these series have no anchoring metadata in Navigator. While I quickly created it with QuickNII and used the Merge_s to apply it on Navigator data, everything working fine, it turns out I can not upload the result. Series are set to public (which also means read-only) and I don't have the privileges to change that. Project principals are @blixilla @Majpuc and Trygve, they can unlock the series by setting them private.

**Comment by Tevemadar** [comment]
On a side note, a tiny example is ready,
http://www.nesys.uio.no/NonLinTest/filmstripzoom.html?atlas=300000&series=423&preview=ABAMousev2Preview.png automatically loads a (mockup) nonlinear anchoring for series 423. There is no trigger/customization in the link, page simply tries to load nonlinear data and either finds it or not.

**Comment by blixilla** [comment]
I have now set H200 as private, hope this helps!

**Comment by Tevemadar** [comment]
@blixilla thank you, I uploaded the metadata. It can be reverted to public if needed.

**Comment by Tevemadar** [comment]
Works, direct link will be this: http://www.nesys.uio.no/NonLinTest/filmstripzoom.html?atlas=200000&series=5946,5947&preview=WHSRatv2Preview.png
However as long as series is private, you will have to login via http://www.nesys.uio.no/NonLinTest (and use the link above as "LocaliZoom link").

**Comment by blixilla** [comment]
Thanks, I have reverted it back to public now. Is it possible to switch the view from outline to atlas in this link, and remove the 'anchors'? Also, I see that the original QuickNII anchoring is what you see in the filmstrip below, is it possible to change this, too?

**Comment by Tevemadar** [comment]
Yes-yes-no.
I can make starting opacity a parameter in the link, and I can also make a simple, viewing-only version, where no anchoring/annotation happens, tools and pins are hidden.
The filmstrip itself can not show the nonlinear adjustments, that would require such changes in Navigator that did not happen in the past 5 years, so it is a safe bet that it won't be ready this week either. What I can do is making it 100% transparent by default or disable completely, and/or make any of that configurable via a parameter in the link.

**Comment by blixilla** [comment]
This sounds good. A simple viewing-only version with starting opacity in the link (would be good if the atlas is semi-transparent by default) and default 100 % transparent filmstrip, would meet our needs.

**Comment by Tevemadar** [comment]
It can be tested now:

- adding parameter `view` disables annotation controls and hides the pins
- adding parameter `opacity=<number>` sets the colorful overlay, with given opacity. Values are 0-100, integral numbers, where 0 is fully transparent, 99 is almost fully opaque and 100 toggles outlines (but that is the automatic setting anyway, when the parameter is not present at all)

Parameters are separated by ampersand. Example link: http://www.nesys.uio.no/NonLinTest/filmstripzoom.html?atlas=200000&series=5946,5947&preview=WHSRatv2Preview.png&view&opacity=10

**Comment by blixilla** [comment]
This looks good, and meets our needs for now, thank you!
