### ISSUE TITLE
Wish list for QNonlin tool

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#4]
- Ideally QNonlin should remember last directory location (e.g. for: file > open >, save as. etc.)
- Save button (not just Save As)
- a big request would be to have a scroll over with region names revealed, I'm not sure how possible this is from a technical perspective
In general I really like the tool! Very user friendly and intuitive

**Comment by blixilla** [comment]
Agree with Sharon!
- Would be awesome to save/transfer markers (and their new placements) to neighbouring sections, as these sections often are very similar.

**Comment by ingrre** [comment]
Agree with the above. It would also be great to have the following implemented: 

- Undo-functionality (removing or adding a marker often changes the surrounding template, it would therefore be great to be able to try out and redo as we go). 
- Quick 'n easy way to turn on/off template and outline (as the h/v as hotkeys in QuickNII). Would i.e. be awesome to be able to turn the outline on/off without pulling the slider all the way through the template.


Two things probably not possible, but I shamelessly mention it anyways: 
- The ability to remove parts of template showing areas not visible in the section image (ie spinal tract or hypothalamus). 
- (An even more drastic suggestion, perhaps:) the ability to split the template for those section images where parts are physically disconnected.

**Comment by Majpuc** [comment]
This issue was splitted in different new issues on dec12_2019
