### ISSUE TITLE
VisuAlign-non linear problems

### ISSUE THREAD

**Issue by blixilla** [Neural-Systems-at-UIO/VisuAlign#5]
- not able to open earlier work (it won't even let me choose the atlas appropriate for the file)
- it crashes when I move to a new section
- getting slow after 20-30 markers (several seconds for each command)
- it crashed when I tried to start again after the computer went in sleep mode
- it seems to be lagging in 'atlas mode' (not in 'outline mode')

I worked with horizontal Timm-thionine sections when experiencing these problems.

**Comment by ingrre** [comment]
- specific sections will not be opened by navigating with arrows (up/down), meaning they are not possible to view/find again. VisuAlign suddenly does not go by increments of 1 and just skips them. Seems as the sections that are skipped are sections that have been anchored (NL) and contain >10 markers.

**Comment by sharoncy** [comment]
Question for Gergely - would it help to work locally, rather than via the server? I also had problems with a dataset that I didn't experience problems with previously...

**Comment by sharoncy** [comment]
Users should save the dataset locally and work from there (not via a server)

**Comment by Tevemadar** [comment]
@blixilla @ingrre please try the new version
- Spinner control did not detect release of mouse button during high CPU utilization, and kept rolling numbers. Replaced with a simple pair of buttons ("<" and ">")
- Atlas resolution was not set after manually picking an atlas (in case of old JSON files from QuickNII). Atlas resolution is set and stored now
- Missing atlas resolution caused a crash after loading dataset. Now it is taken from the atlas when missing

There may be a minor improvement in performance, but stability issues are more important now.
