### ISSUE TITLE
MeshView v3 [new version] on mac

### ISSUE THREAD

**Issue by ingrre** [Neural-Systems-at-UIO/VisuAlign#52]
New MeshView version (https://www.nesys.uio.no/MeshView/meshview.html?atlas=ABA_mouse_v3_root) does not work when trying to open it on my mac (neither with chrome nor firefox). Flash is allowed and "connection is secure". 

The old version (http://www.nesys.uio.no/MeshGen/MeshView.html?bitlas=ABAv3.bitlas) works very well. 

What is it that I am doing wrong? 

This is how it looks: 
![image](https://user-images.githubusercontent.com/38322594/79949023-24b36c80-8475-11ea-8b86-4786c1cd580c.png)

**Comment by Tevemadar** [comment]
> What is it that I am doing wrong?

Presumably nothing. MeshView is not tested extensively on Mac, although it worked at some point of time in the past, even displayed something on an iPad. So there is hope that it can be fixed to work again. One memory from the past: I remember a browser where MeshView did not show anything while loading, but everything worked correctly after rotating the atlas. So just keep the mouse button pressed somewhere at the middle of the screen and move the mouse a little. Probably it will not work, but it is easy to try.
As we have no Macs at home I will have to check it from the office, based on the emails from the past few days it may happen soon.

**Comment by ingrre** [comment]
Thanks for responding so quickly! I tried out rotating the atlas as you said, without response. I'm alright with the old version for now though, good luck with the fix.

**Comment by Tevemadar** [comment]
Ok, I see the issue. Ironically I tested MeshView on Mac with Safari only, and there it works. For the same reason it appears on iPad too (just misses touch controls).

**Comment by Majpuc** [comment]
@Tevemadar Do we have a conclusion?

**Comment by Majpuc** [comment]
@ingrre Clear cached data worked. See: https://support.mozilla.org/en-US/kb/how-clear-firefox-cache

**Comment by Tevemadar** [comment]
It's expected to work now, fixed on both NeSys and HBP.
