### ISSUE TITLE
Encode the Atlas name and version in all QNII anchoring files

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/VisuAlign#53]
We need to be able to track with Atlas name and version was used for anchoring in QNII. Implementation of this is needed for all versions of QNII as seen in image bellow for WHSv3

![image](https://user-images.githubusercontent.com/46992863/79974886-5a1e8100-849a-11ea-918d-69545259204d.png)

**Comment by Majpuc** [comment]
@Tevemadar would be good to implement if it does not take long time

**Comment by Tevemadar** [comment]
If there is a way to make QuickNII v2.2 not to store this data, that's a bug and please providea  description of how to reproduce.

**Comment by Majpuc** [comment]
It is working fine with all versions of QuickNIIv2.2.
