### ISSUE TITLE
MeshView - add version numbers!

### ISSUE THREAD

**Issue by marovst** [Neural-Systems-at-UIO/VisuAlign#55]
(NB! This have already been implemented and this issue is created for reporting purposes)

The newest update changed scaling to be relative to the whole brain instead of active structures.  All my analyses have been done with the scaling of the previous version, thus to keep image extraction from MeshView consistent it would be good to have previous versions as well. 

Can previous versions of MeshView be added?

**Comment by Majpuc** [comment]
I suggest to have a clear version number for MeshView and differentiate from flash based to new version and also have one access page (Meshview vs MeshGen pages are confusing)

**Comment by Tevemadar** [comment]
A version number has been added to the title of tab/window (https://www.nesys.uio.no/MeshView/meshview.html?atlas=ABA_root - "NXTView v0.75" at the moment).

**Comment by Majpuc** [comment]
Nice. Could you gather all NTXView rat (v2 and v3) and mouse on the same page ?
![image](https://user-images.githubusercontent.com/46992863/90014938-231de680-dca8-11ea-8ca2-d6d835b51e33.png)

**Comment by Majpuc** [comment]
We need to change names of the versions here:
- ABA Mouse v3 2017 all structures is OK
- ABA Mouse v3 outline only is OK
- ABA Mouse v3 with outlineobject (root): is this v3 2015?
- ABA Mouse v3: 2015? 2017? redundant?
- Add WHSRat v3

**Comment by Tevemadar** [comment]
Please refrain from reusing issues just because the expression "version number" may apply to software and atlas alike.
