### ISSUE TITLE
Atlasmaps that extend to edge of image

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#6]
If an atlas map falls outside of the section image, the atlas map remains anchored outside (cannot be dragged in). Is there a solution for this? The only solution I can see is to reanchor with QuickNII so that the atlas template is within the image boundaries...

**Comment by sharoncy** [comment]
There are solutions for this - Gergely will look into it.

**Comment by sharoncy** [comment]
I discussed this with Gergely. For now users should anchor sections so that the atlas maps fall within the boundaries of the sections (the autocropping feature in Transform makes this more likely, in some cases it may be helpful not to autocrop images). In the long run, Gergely will implement support to solve this, for example by adding a border around sections...

**Comment by Majpuc** [comment]
Do you have some update here?

**Comment by Majpuc** [comment]
@Tevemadar Did you implement this?

**Comment by Tevemadar** [comment]
No, this is not implemented fully. VisuAlign allows manipulating an extra 10% border around images, so data created in the current release will be compatible with the future one, but that border displays only empty space now.

**Comment by Majpuc** [comment]
The 10% border around the image is satisfactory for now.

**Comment by Majpuc** [comment]
closed 03.09.2021
