### ISSUE TITLE
QuickNII: region names on scroll over with outlines switched on

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#60]
More info is provided in the email. Is it possible to display the region names on scroll over with the region outlines switched on? This would be really helpful for exploring the boundaries between regions.

**Comment by Tevemadar** [comment]
For this one I suggest using VisuAlign, it shows atlas labels in outline mode too.

**Comment by sharoncy** [comment]
Thanks Gergely. I actually realised this today too.

**Comment by Majpuc** [comment]
issue closed 03.09.2021
