### ISSUE TITLE
Developmental mouse atlases implemented in QuickNII

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/VisuAlign#69]
Request from Ingvild: 
I am working on a voucher project where we have a lot of developmental data (mice of 17, 25 and 35 days). We have been allowed to use a set of atlases reconstructed from Allen Institute's developmental mouse brain atlases, shared (but under embargo) by David Young through EBRAINS. These include atlases from mice of 4, 14, and 28 days, as well as an adult atlas delineated according to developmental ontology. The volumes shared by David Young are in .mhd and .raw format, I managed to open them in ITK-snap so I hope they can readily be transformed to formats that can be used in QuickNII and VisuAlign.

**Comment by Majpuc** [comment]
On the technical side there was a discrepancy. http://help.brain-map.org/display/devmouse/API explicitly says

> annotation: uint (32bit) structural annotation volume matching the atlasVolume [...]

which is true for data they provide at http://download.alleninstitute.org/informatics-archive/current-release/mouse_annotation/

But, in case of the ones you acquired,annotation volumes for P4 and P14 are 16-bit. As ontology graphs from http://help.brain-map.org/display/api/Atlas+Drawings+and+Ontologies use 32-bit values and meant for the published volumes, there is no straightforward way to tell how the interpretation has changed for these unpublished/preliminary ones. Since the colors themselves look okay both for an expert (you) and a layman (me), there must be some systematic change in the background, but we need an actual documentation about it.
technical side there was a discrepancy. http://help.brain-map.org/display/devmouse/API explicitly says

> annotation: uint (32bit) structural annotation volume matching the atlasVolume [...]

which is true for data they provide at http://download.alleninstitute.org/informatics-archive/current-release/mouse_annotation/

But, in case of the ones you acquired and have on lagringshotell, annotiation volumes for P4 and P14 are 16-bit. As ontology graphs from http://help.brain-map.org/display/api/Atlas+Drawings+and+Ontologies use 32-bit values and meant for the published volumes, there is no straightforward way to tell how the interpretation has changed for these unpublished/preliminary ones. Since the colors themselves look okay both for an expert (you) and a layman (me), there must be some systematic change in the background, but we need an actual documentation about it.

**Comment by Majpuc** [comment]
@ingvildeb Could you  validate? can we close the ticket?

**Comment by ingvildeb** [comment]
Yes, everything appears to be correct.
