### ISSUE TITLE
display region names in VisuAlign non-lin

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/VisuAlign#7]
In order to ease the non-linear registration, our users at Jackson lab would like to be able to read the atlas region name when ponting the the mouse to a region.

**Comment by Majpuc** [comment]
Validated January 13th 2020

**Comment by sharoncy** [comment]
The atlas maps from VisuAlign contain version info, the atlas maps from QuickNII do not and it is not possible to implement this. Both the JSON and XML files contain version info. Ideally we should implement support for automatic version recognition in Nutil Quantifier, either from the JSON/XML file or based on the atlas maps. No conclusion made at this point but this should be taken into account in future developments.
