### ISSUE TITLE
v0.2

### ISSUE THREAD

**Issue by Tevemadar** [Neural-Systems-at-UIO/VisuAlign#72]
This version allows users to manually input pixel size and grid spacing.

* pixel size is expressed in nanometers (1000 nm = 1 um) because fractions are not supported
* grid spacing is expressed in micrometers
* both of them are isotropic, apply to horizontal and vertical axes

**Comment by sharoncy** [comment]
Thanks! I will test!

**Comment by sharoncy** [comment]
Thanks! I will test!

**Comment by sharoncy** [comment]
Thanks! I will test!

**Comment by sharoncy** [comment]
I have tested and it works great, thanks!

The next step would be to implement adjustable atlas hierarchies. I thought I could start working without this, but in practise it's too time consuming to work out which boundaries I ought to be using. The finest level of granularity is too detailed for the datasets I'm working on. Really great if you could implement this ASAP.
