### ISSUE TITLE
Hierarchy filtering

### ISSUE THREAD

**Issue by Tevemadar** [Neural-Systems-at-UIO/VisuAlign#73]

**Comment by sharoncy** [comment]
Any progress here? I am going to start working with the tool in the next few days...

**Comment by sharoncy** [comment]
Gergely has implemented this in the latest version (NESYS_Tools\QControl or NESYS_Tools\QControl.zip). Is there a way to quickly switch to the finest level of granularity of the atlas without having to manually open all the levels? @Tevemadar

**Comment by Tevemadar** [comment]
There is no such shortcut, but a way to go through the list faster is to use the cursor keys. After clicking into the list, up/down arrows simply move in the list and left/right arrows close/open the hierarchy (when closing branches the blue highlight may disappear, in that case, click into the list again). While a bit counter-intuitive, opening a large number of branches often requires less button presses if you move from the bottom of the list upwards as this way you don't have to traverse the labels on the finest level.

**Comment by sharoncy** [comment]
Gergely's tip of working from the bottom and up was a good one. I have created a new issue for transferring customised hierarchy levels between files. I will close this issue.
