### ISSUE TITLE
Update MeshView launch page and atlases

### ISSUE THREAD

**Issue by Tevemadar** [Neural-Systems-at-UIO/VisuAlign#81]
> Nice. Could you gather all NTXView rat (v2 and v3) and mouse on the same page ?
> ![image](https://user-images.githubusercontent.com/46992863/90014938-231de680-dca8-11ea-8ca2-d6d835b51e33.png)

and 

> We need to change names of the versions here:
> - ABA Mouse v3 2017 all structures is OK
> - ABA Mouse v3 outline only is OK
> - ABA Mouse v3 with outlineobject (root): is this v3 2015?
> - ABA Mouse v3: 2015? 2017? redundant?
> - Add WHSRat v3

**Comment by Tevemadar** [comment]
Partially done https://www.nesys.uio.no/MeshView

**Comment by Majpuc** [comment]
@Tevemadar Would be nice to close this one ;)

**Comment by Majpuc** [comment]
03.09.2021. Other priorities right now

**Comment by Majpuc** [comment]
closed. Please use MeshView on hbp not uio.no
