### ISSUE TITLE
VisuAlign - Viral tracing experiments registered with non-linear anchoring

### ISSUE THREAD

**Issue by marovst** [Neural-Systems-at-UIO/VisuAlign#85]
I have a batch of non-linear coordinate files that needs to be uploaded to N3. 

The coordinate files can be found in the following folder:
Z:\HBP_Curation\QuickNII_projects\Projects\Incomplete_projects\2017-2019_ToccoChiara_Thy1Cre\2020_deliveries\Viral_injection_nonlin

Pre-fixes corresponds to position in N3.

**Comment by Majpuc** [comment]
The Localizoom links will be created but are not uploaded to N3 ;) (just stored in another repository)

**Comment by Tevemadar** [comment]
I have no access to project 1501, but theoretically they are released now.
They require login (https://www.nesys.uio.no/NonLinTest), and after that https://www.nesys.uio.no/NonLinTest/filmstripzoom.html?atlas=300100&series=7557 and the like.

**Comment by Majpuc** [comment]
@marovst can you validate that the links are working properly? Thanks!

**Comment by marovst** [comment]
@Majpuc the links are working properly. Thanks for the help.
