### ISSUE TITLE
QControl functionality - points

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#86]
- functionality for marking up many points at once
- adjustable question mark colour (maybe same colour as the grid, they are currently black, which is the same colour as the NeuN stain and hard to see).

**Comment by sharoncy** [comment]
It is time consuming to mark up points one by one. As we discussed at a sw dev meeting, it would be useful to enable mark-up of all the points within a region at once, but to leave the points close to the borders unmarked. This is important to prevent bias, as it will ensure users have to manually consider the accuracy at the borders, which is where most of the uncertainly and inaccuracy is likely to be. This feature will be particularly useful for coarser levels of granularity of the atlas.

**Comment by Tevemadar** [comment]
NESYS_Tools\QControl-v0.6 can pre-fill inner parts of regions now.
It happens when a section has invalidated QC data:

- opening sections with no matching QC data (empty or old)
- changing grid spacing
- using the reset options in Edit menu (resetting current section or entire series)

**Comment by sharoncy** [comment]
Validated 10.03.21.
