### ISSUE TITLE
QControl - define the point spacing based on the reference atlas

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#88]
It would be best if the point spacing in the QControl tool could be calculated based on the reference atlas, and not based on the scale of the atlas map images. Users typically do not remember how they resized their images.

**Comment by sharoncy** [comment]
I have tested the latest version of the QControl tool (with hierarchy implemented). It would be great if the tool could calculate the point spacing based on the reference atlas, and not based on the scale of the section images. Some of the image series have been resized with varying resize factors, so that the scale changes from image to image. As I didn't do the resizing myself it is difficult to trace back.

**Comment by Tevemadar** [comment]
NESYS_Tools\QControl-v0.6 specifies grid spacing in voxels. For AMBA that means 25 um stepping.
The new grid is not compatible with the old one, QC v0.6 attempts to ignore content created with v0.5 or earlier.

**Comment by sharoncy** [comment]
Thanks, I'll try it out this week.

**Comment by sharoncy** [comment]
This feature works well. Validated 10.03.21.
