### ISSUE TITLE
QuickMask: hemisphere masks based on VisuAlign registration

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#89]
I tested the QuickMask tool for generating left/right hemisphere masks and it works well. However, it would be really great if the hemisphere masks could be generated based on the nonlinear registration and not just the QuickNII output.

**Comment by sharoncy** [comment]
Currently, QuickMask generates masks with white on the left side and black on the right side so that the colour corresponding to the area to include in the analysis will vary depending on whether the brain is anchored to the right or left hemisphere. Brianna has requested that QControl generate masks with a set colour corresponding to the area to include in the analysis, irrespective of whether the sections are anchored to the right or left hemisphere. I guess this may be possible in relation to implementing support for the nonlinear registration?

**Comment by Majpuc** [comment]
Status on 03.09.2021. Priority is on WebAlign. We will return to this

**Comment by sharoncy** [comment]
Gergely has implemented support for nonlinear alignment. It works well. Close this issue. 06.01.22.
