### ISSUE TITLE
VisuAlign - Timm/thionin sections registered with non-linear anchoring (H201)

### ISSUE THREAD

**Issue by blixilla** [Neural-Systems-at-UIO/VisuAlign#90]
I have a non-linear coordinate file that I would like to get a LocaliZoom-link for.

The coordinate file can be found on imb-neuroinf:
Y:\hbp-02421_timm_thionine\0000_FINAL-Timm-Thionin\H201\QNII_anchoring\H201_TimmThionin_sagittal_US_new_VisuAlign_CHB_all.json

This corresponds to files in three blocks on N3: 841_2786_H201a, 841_2786_H201b and 841_2786_H201c

**Comment by Tevemadar** [comment]
Done, https://www.nesys.uio.no/NonLinTest/filmstripzoom.html?atlas=200100&series=4906,5253,5254
However some of the c-images seem to load much-much slower than the other two, like 069.

**Comment by blixilla** [comment]
Thank you for the link. Yes, it is really slow, and when it is done loading I see both atlas and markers, but the atlas is not adjusted according to the markers. Did you get that, as well?

**Comment by blixilla** [comment]
Hi again @Tevemadar ,

I was wondering if you could also create a link for the following Timm-series (H109) on imb-neuroinf:
Y:\hbp-02421_timm_thionine\0000_FINAL-Timm-Thionin\H109\QNII_anchoring\H109_Timm_new_horizontal_VisuAlign_CHB_all.json

This corresponds to files in one block on N3: 841_4404_H109

Thanks in advance.

**Comment by blixilla** [comment]
Hi @Tevemadar ,
Unfortunately I made a mistake when asking you to create the LocaliZoom link for H201, directed you to the wrong blocks on N3 (the old versions, not the '_new'), sorry about this. The information below should be correct: 

The coordinate file can be found on imb-neuroinf:
Y:\hbp-02421_timm_thionine\0000_FINAL-Timm-Thionin\H201\QNII_anchoring\H201_TimmThionin_sagittal_US_new_VisuAlign_CHB_all.json

This corresponds to files in three blocks on N3: 841_2786_H201a_new, 841_2786_H201b_new and 841_2786_H201c_new

Would you be able to correct my mistake and create a new link?

**Comment by Majpuc** [comment]
@blixilla we will have to come back on this. Other priorities until M18 review

**Comment by Majpuc** [comment]
As this data will be uploaded to EBRAINS, new viewer links will be created. Issue closed 31.05.2022
