### ISSUE TITLE
Issue of loading outlines

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/VisuAlign#93]
A VisuAlign user is having trouble with one series where for some of the sections,  the outlines are not loaded. Or the lag time for loading the outlines is very long. The user command window is provided in case  something can be spotted there.
[error report tg5174.docx](https://github.com/Neural-Systems-at-UIO/VisuAlign/files/5518134/error.report.tg5174.docx)
The series can be found here: Y:\NESYS_Active_projects\2019_ AD-McGillAPP rats-Puchades\20191015_CHAT\TG5174\QNII_series\QNII_TG5174_final(J)\QNII_TG5174_final

Json: TG5174_final_cur281020

**Comment by Majpuc** [comment]
In addition, I have the same issue on another series, running all locally. It seems to be an "Exception in thread "JavaFX Application Thread" java.lang.NullPointerException"
![image](https://user-images.githubusercontent.com/46992863/98811936-eafe7f00-2421-11eb-8ced-e717de02868c.png)

**Comment by Tevemadar** [comment]
NESYS_Tools\QNonLin-Standalone does not produce errors with TG5174_final_cur281020.json, I paged through all 78 sections.
A thing which may matter: WHSv3 atlas has been updated on the 23rd of January. Older copies of VisuAlign will die on some of the sections where the ear is visible (around 62-63 perhaps).

**Comment by Majpuc** [comment]
I have downloaded VisuAlign this summer, so it is not an old version. Could it be something else?

**Comment by Tevemadar** [comment]
NITRC versions have been updated.
