### ISSUE TITLE
Z-spread function independent of Nutil 

### ISSUE THREAD

**Issue by marovst** [Neural-Systems-at-UIO/VisuAlign#95]
Would there be possible to have point coordinates spread along an axis independent of Nutil workflow? E.g. point coordinates extracted from localizoom. 

Reason for this feature: We have point coordinates extracted with LocaliZoom in sagittal view and we would like to compare them to each other in coronal view as well. 

Need for z-spread functionality
The input data are x,y,z coordinate lists (generated using LocaliZoom) in which all points are aligned in a 2-D plane. We need to randomize each z-coordinate within a defined distance from this plane (reflecting the thickness of the section from which the data were recorded, typically 50-200 micrometer), as an added or subtracted value in a direction which is perpendicular to the original 2-D section plane.

[Coordinates_112229814_SSpul.txt](https://github.com/Neural-Systems-at-UIO/VisuAlign/files/5574009/Coordinates_112229814_SSpul.txt)

**Comment by sharoncy** [comment]
@leuat will look at this.

**Comment by leuat** [comment]
Script has been created and sent to Martin. Please re-open if there are any issues, @marovst
