### ISSUE TITLE
VisuAlign freezes on certain slides

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/VisuAlign#98]
On a series where all sections are adjusted, Visualign 0.8 freezes on certain  delineation. The background image is updating but not the atlas which stays on the previous image. This behavior is seen both when running with images locally and with images on the server.
Series found here: Y:\NESYS_Active_projects\2019_ AD-McGillAPP rats-Puchades\20191015_CHAT\TG5187\QNII\QNII_TG5187_v4
Json file: TG5187_251126_MAP2

**Comment by Tevemadar** [comment]
Fixed on Nov 12 already, in ```VisuAlign-v0_8-WHS_Rat_v3_fix.zip``` (and ```VisuAlign-v0_8-WHS_Rat_v3_fix.dmg``` for Mac).
