### ISSUE TITLE
QControl output

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/VisuAlign#99]
Request for feature to export QControl output (accuracy, uncertainty, inaccuracy, etc, per region, slice, whole brain, etc). As it stands, I haven't thought too much about what should be included in the output, how it should be formatted, etc, so it would be great if you could implement something that makes sense to you, and then we can discuss it at a later date. I will send you an example file to work with.

**Comment by Tevemadar** [comment]
NESYS_Tools\QControl-v0.5 has statistical output for the active section now. Select ```Section statistics``` from the ```File``` menu, and a tabulator-delimited text file is created next to the series with ```_stats.txt``` ending added to the original image name.  
Example: ```119-CKT-1-Thionine-11-15-15-05-09.png``` will have ```119-CKT-1-Thionine-11-15-15-05-09.png_stats.txt``` created.
Output contains per-region (only the ones present in the given section), per-status (empty, okay, wrong, undecidable) counts.

(And ```Export statistics``` continues to deliver per-section, per-status counts)

**Comment by sharoncy** [comment]
Thanks @Tevemadar. I have done a quick test and it works as described. The plan is to use the QControl output to streamline the postprocessing of the Nutil reports (to apply accuracy/inaccuracy/uncertainty cutoffs, etc). We can brainstorm how best to do this tomorrow. I have some ideas but it would be good to have everyone's input. @leuat @Majpuc

**Comment by Tevemadar** [comment]
New update: ```Export statistics``` generates the ```_stat.txt``` files for all sections in one step and also a single sheet for the entire series. This latter file has ```_stat.txt``` derived from the series-descriptor. For example ```AB_QControl_Thionine_customised.json``` will have ```AB_QControl_Thionine_customised_stats.txt``` generated as output.
* QControl doesn't really tell or ask anything at the moment, the files just appear
* the files are meant to be opened with or simply copy-pasted to Excel
* statistics for structures which are not present in a given section are intentionally left blank - let me know if filling with zeroes would be better
* it's possible to implement a flipped output (sections in rows and structures in columns) if needed - that may result in a more compact sheet.

**Comment by sharoncy** [comment]
This is great, we should be able to implement Nutil support for these. Please update the terms to: N/A (for empty), Accurate (Okay), Inaccurate (wrong), Uncertain (undecidable) and then we can close this issue.

**Comment by Tevemadar** [comment]
Labels have been changed now.

**Comment by sharoncy** [comment]
I have done some testing here and made some requests relating to the stats. See issues 124 and 125. As I have transferred these to new issues, this one can be closed. SY, 10.03.21.
